name: Development

on:
  push:
    branches:
    -main

jobs: # dictionary
  build-test:
    #add a build server of ubuntu-latest
    runs-on: ubuntu-latest

    steps: # array
      # add a new step checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # add a new step to install .NET SDK 7
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    # add a new step to restore nuget packages
    - name: Restore nuget packages
      run: dotnet restore
    
    # # add a new step to build the entire solution
    # - name: Build solution
    #   run: dotnet build
    
    # # add a new step to test the solution
    # - name: Test solution
    #   run: dotnet test

    # add a new step to build the entire solution with Release configuration
    - name: Build solution
      run: dotnet build --configuration Release

    # add a new step to test the solution with Release configuration
    - name: Test solution
      run: dotnet test --configuration Release

    # # add a new step to publish the solution with Release configuration > src와 test 모두 publish 하게 됨
    # - name: Publish solution
    #   run: dotnet publish --configuration Release
    
    # add a new step to publish src/WebApi with Release configuration
    - name: Publish WebApi
      run: dotnet publish --configuration Release --output src/WebApi/bin/Release/net5.0/publish src/WebApi/WebApi.csproj

